name: flutter_clean_architecture
description: Flutter project developed during a Clean Architecture + TDD course

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    # Service locator
  get_it: ^5.0.1

  # Bloc for state management
  flutter_bloc: ^6.0.6

  # Value equality
  equatable: ^1.2.5

  # Functional programming thingies
  dartz: ^0.9.2

  # Remote API
  connectivity: ^2.0.1
  http: ^0.12.2

  # Local cache
  shared_preferences: ^0.5.12+4

  # Dart Annotations
  meta: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  lint: ^1.3.0

flutter:
  uses-material-design: true
